name: Deploy Serverless Functions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Create minimal supabase/config.toml
        run: |
          mkdir -p src/supabase
          echo "project_id = \"${{ secrets.PROJECT_ID }}\"" > src/supabase/config.toml

      - name: Change to src directory
        run: cd src

      - name: Run serverless-push.sh
        run: |
          chmod +x ./serverless-push.sh
          ./serverless-push.sh
        working-directory: src